name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  push:
    branches:
      - master
      - dev
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm i && npm run build:playground
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          folder: packages/playground/dist
          branch: static
