/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./../components/Footer/index.vue')['default']
    InpaintingEditor: typeof import('./../components/InpaintingEditor/index.vue')['default']
    MsgItem: typeof import('./../components/MsgItem/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Welcome: typeof import('./../components/Welcome/index.vue')['default']
  }
}
