/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./../components/Footer/index.vue')['default']
    InpaintingEditor: typeof import('./../components/InpaintingEditor/index.vue')['default']
    MjForm: typeof import('./../components/MjForm/index.vue')['default']
    MjModal: typeof import('./../components/MjModal/index.vue')['default']
    MsgItem: typeof import('./../components/MsgItem/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Welcome: typeof import('./../components/Welcome/index.vue')['default']
  }
}
