name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  push:
    branches:
      - master
      - dev
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Build
        run: pnpm i && pnpm build:playground
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          folder: packages/playground/dist
          branch: static
